name: Run Python Scripts

on:
  workflow_dispatch:  # Triggered manually
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'  # Run every 12 hours

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt  # Replace 'path/to/requirements.txt' with the actual path

      - name: Run Python Scripts
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python Symbols.py
          python StkData.py
          python Updated_Mktcap.py
          python promoter_pledge.py
          python insider_trading_data.py

      - name: Create or update CSV files
        run: |
          # Assuming CSV files are in the same directory
          for file in *.csv; do
            [ -e "$file" ] || continue
            echo "Processing $file"
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add "$file"
            git commit -m "Automated commit - $file" || true
          done
          git push
