name: Run Scripts

on:
  workflow_dispatch:
    inputs:
      run-now:
        description: 'Run scripts immediately'
        required: false
        default: 'false'

  schedule:
    - cron: '0 * * * *' # Schedule every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the Python version needed

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run insider_trading_data.py
        run: python insider_trading_data.py

      - name: Wait for 20 minutes
        if: ${{ github.event_name == 'schedule' }}
        run: sleep 1200  # 1200 seconds = 20 minutes

      - name: Run Promoter_Pledge.py
        run: python Promoter_Pledge.py
